// Generated by harness-setup skill. Rules derived from project profile.
// HARNESS:Q2_ENFORCEMENT={{Q2_ENFORCEMENT}}
// 도메인 기반 아키텍처 검증 스크립트 템플릿
//
// 사용법: npx tsx scripts/structural-test.ts
// 규칙:
//   1. 도메인 간 직접 import 금지 (이벤트 또는 공유 인터페이스를 통해 통신)
//   2. 공유 모듈(SHARED_DIRS)은 모든 도메인에서 import 가능
//   3. 공유 모듈이 도메인을 import하는 역방향은 금지

import * as fs from 'fs';
import * as path from 'path';

// {{SHARED_DIRS}} — 프로필의 sharedDirs로 치환 (기본값: ['shared'])
const SHARED_DIRS: string[] = ['shared'];

// {{PATH_ALIAS}} — 프로필의 pathAlias로 치환 (예: '@/' 또는 ['@/', '~/'])
// 문자열이면 단일 alias, 배열이면 다중 alias
const PATH_ALIAS: string | string[] = '@/';

// {{SRC_ROOT}} — 프로필의 srcRoot로 치환 (예: './src')
const SRC_ROOT = './src';

// --- 이하 코드는 치환 없이 그대로 사용 ---
// 도메인 목록은 하드코딩하지 않고 실행 시점에 SRC_ROOT의 최상위 디렉토리에서 발견한다.
// 도메인 추가/삭제 시 이 스크립트를 수정할 필요가 없다.

interface Violation {
  file: string;
  line: number;
  fromDir: string;
  toDir: string;
  reason: string;
  importStatement: string;
}

function getTopDirs(srcDir: string): string[] {
  return fs
    .readdirSync(srcDir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name);
}

function getFilesRecursive(dir: string): string[] {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  return entries.flatMap((entry) => {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) return getFilesRecursive(fullPath);
    if (/\.(ts|tsx)$/.test(entry.name) && !/\.test\.(ts|tsx)$/.test(entry.name)) {
      return [fullPath];
    }
    return [];
  });
}

function resolveTopDirFromRelativePath(
  filePath: string,
  importPath: string,
  srcDir: string,
  topDirs: string[],
): string | null {
  const fileDir = path.dirname(filePath);
  const resolved = path.resolve(fileDir, importPath);
  const relative = path.relative(srcDir, resolved);
  if (relative.startsWith('..')) return null;
  const topFolder = relative.split(path.sep)[0];
  return topDirs.includes(topFolder) ? topFolder : null;
}

function findViolations(srcDir: string): Violation[] {
  const violations: Violation[] = [];
  const topDirs = getTopDirs(srcDir);
  const aliases = Array.isArray(PATH_ALIAS) ? PATH_ALIAS : [PATH_ALIAS];
  const aliasPatterns = aliases.map((a) => a.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  const aliasRegex = new RegExp(`from\\s+['"](?:${aliasPatterns.join('|')})([\\w-]+)`);
  // import 및 re-export 구문 모두 감지: import ... from '...' / export { ... } from '...'
  const relativeRegex = /(?:import|export)\s+.*from\s+['"](\.\.?\/[^'"]+)/;

  for (const currentDir of topDirs) {
    const isSharedSource = SHARED_DIRS.includes(currentDir);
    const files = getFilesRecursive(path.join(srcDir, currentDir));

    for (const file of files) {
      const content = fs.readFileSync(file, 'utf-8');
      const lines = content.split('\n');

      lines.forEach((line, idx) => {
        let importedDir: string | null = null;

        // 1. alias import 검사: @/domain/...
        const aliasMatch = line.match(aliasRegex);
        if (aliasMatch && topDirs.includes(aliasMatch[1])) {
          importedDir = aliasMatch[1];
        }

        // 2. 상대 경로 import 검사: ../../domain/...
        if (!importedDir) {
          const relMatch = line.match(relativeRegex);
          if (relMatch) {
            importedDir = resolveTopDirFromRelativePath(file, relMatch[1], srcDir, topDirs);
          }
        }

        if (!importedDir) return;
        if (importedDir === currentDir) return; // 같은 도메인 내 import는 허용
        if (SHARED_DIRS.includes(importedDir)) return; // 공유 모듈 import는 항상 허용

        // 여기 도달 = importedDir는 다른 도메인
        if (isSharedSource) {
          violations.push({
            file: path.relative(srcDir, file),
            line: idx + 1,
            fromDir: currentDir,
            toDir: importedDir,
            reason: '공유 모듈은 도메인을 import할 수 없음 (역방향 의존)',
            importStatement: line.trim(),
          });
        } else {
          violations.push({
            file: path.relative(srcDir, file),
            line: idx + 1,
            fromDir: currentDir,
            toDir: importedDir,
            reason: '도메인 간 직접 import 금지 (이벤트/공유 인터페이스로 통신)',
            importStatement: line.trim(),
          });
        }
      });
    }
  }

  return violations;
}

// 실행
const violations = findViolations(SRC_ROOT);

if (violations.length > 0) {
  console.error('❌ 도메인 아키텍처 위반 발견:\n');
  violations.forEach((v) => {
    console.error(`  ${v.file}:${v.line}`);
    console.error(`    ${v.fromDir} → ${v.toDir} (금지: ${v.reason})`);
    console.error(`    ${v.importStatement}\n`);
  });
  console.error(`총 ${violations.length}건의 위반`);
  process.exit(1);
} else {
  console.log('✅ 도메인 아키텍처 규칙 검증 통과');
}
