// Generated by harness-setup skill. Rules derived from project profile.
// FSD (Feature-Sliced Design) 아키텍처 검증 스크립트 템플릿
//
// 사용법: npx tsx scripts/structural-test.ts
// 이 파일은 템플릿이다. SKILL.md가 프로필 기반으로 LAYER_RULES를 치환하여
// 프로젝트의 scripts/structural-test.ts에 생성한다.

import * as fs from 'fs';
import * as path from 'path';

// {{LAYER_RULES}} — 프로필의 architecture.layers.rules로 치환
// 예시 (react-router-fsd 프리셋 기준):
const LAYER_RULES: Record<string, string[]> = {
  'shared':   [],
  'entities': ['shared'],
  'features': ['shared', 'entities'],
  'widgets':  ['shared', 'entities', 'features'],
  'pages':    ['shared', 'entities', 'features', 'widgets'],
  'app':      ['shared', 'entities', 'features', 'widgets', 'pages'],
};

// {{PATH_ALIAS}} — 프로필의 pathAlias로 치환 (예: '@/' 또는 ['@/', '~/'])
// 문자열이면 단일 alias, 배열이면 다중 alias
const PATH_ALIAS: string | string[] = '@/';

// {{SRC_ROOT}} — 프로필의 srcRoot로 치환 (예: './src')
const SRC_ROOT = './src';

// --- 이하 코드는 치환 없이 그대로 사용 ---

type ViolationType = 'layer' | 'cross-slice' | 'public-api';

interface Violation {
  file: string;
  line: number;
  type: ViolationType;
  message: string;
  importStatement: string;
}

function getFilesRecursive(dir: string): string[] {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  return entries.flatMap((entry) => {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) return getFilesRecursive(fullPath);
    if (/\.(ts|tsx)$/.test(entry.name) && !/\.test\.(ts|tsx)$/.test(entry.name)) {
      return [fullPath];
    }
    return [];
  });
}

function getSliceName(filePath: string, layerDir: string): string | null {
  const relative = path.relative(layerDir, filePath);
  const parts = relative.split(path.sep);
  return parts.length > 1 ? parts[0] : null;
}

function resolveLayerFromRelativePath(
  filePath: string,
  importPath: string,
  srcDir: string,
): { layer: string; slice: string | null } | null {
  const fileDir = path.dirname(filePath);
  const resolved = path.resolve(fileDir, importPath);
  const relative = path.relative(srcDir, resolved);
  if (relative.startsWith('..')) return null;
  const parts = relative.split(path.sep);
  const layer = parts[0];
  if (LAYER_RULES[layer] === undefined) return null;
  const slice = parts.length > 1 ? parts[1] : null;
  return { layer, slice };
}

function findViolations(srcDir: string): Violation[] {
  const violations: Violation[] = [];
  const aliases = Array.isArray(PATH_ALIAS) ? PATH_ALIAS : [PATH_ALIAS];
  const aliasPatterns = aliases.map((a) => a.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  // FSD alias 패턴: @/layer/slice/... 또는 @/layer/...
  const aliasRegex = new RegExp(`from\\s+['"](?:${aliasPatterns.join('|')})([\\w-]+)(?:/([\\w-]+))?`);
  // import 및 re-export 구문 모두 감지: import ... from '...' / export { ... } from '...'
  const importOrReExportRegex = /(?:import|export)\s+.*from\s+['"](\.\.?\/[^'"]+)/;
  const relativeRegex = importOrReExportRegex;

  for (const [layer, allowed] of Object.entries(LAYER_RULES)) {
    const layerDir = path.join(srcDir, layer);
    if (!fs.existsSync(layerDir)) continue;

    const files = getFilesRecursive(layerDir);

    for (const file of files) {
      const content = fs.readFileSync(file, 'utf-8');
      const lines = content.split('\n');
      const currentSlice = getSliceName(file, layerDir);

      lines.forEach((line, idx) => {
        let importedLayer: string | null = null;
        let importedSlice: string | null = null;

        // 1. alias import 검사
        const aliasMatch = line.match(aliasRegex);
        if (aliasMatch) {
          importedLayer = aliasMatch[1];
          importedSlice = aliasMatch[2] || null;
        }

        // 2. 상대 경로 import 검사
        if (!importedLayer) {
          const relMatch = line.match(relativeRegex);
          if (relMatch) {
            const resolved = resolveLayerFromRelativePath(file, relMatch[1], srcDir);
            if (resolved) {
              importedLayer = resolved.layer;
              importedSlice = resolved.slice;
            }
          }
        }

        if (!importedLayer) return;

        // 검사 1: 레이어 의존성 방향 위반
        if (importedLayer !== layer && !allowed.includes(importedLayer)) {
          violations.push({
            file: path.relative(srcDir, file),
            line: idx + 1,
            type: 'layer',
            message: `${layer} → ${importedLayer} (상위 레이어 import 금지)`,
            importStatement: line.trim(),
          });
          return;
        }

        // 검사 2: 같은 레이어 내 cross-slice import 금지
        // (shared 레이어는 슬라이스가 없으므로 제외)
        if (
          importedLayer === layer &&
          layer !== 'shared' &&
          currentSlice &&
          importedSlice &&
          currentSlice !== importedSlice
        ) {
          violations.push({
            file: path.relative(srcDir, file),
            line: idx + 1,
            type: 'cross-slice',
            message: `${layer}/${currentSlice} → ${layer}/${importedSlice} (같은 레이어 내 cross-slice import 금지)`,
            importStatement: line.trim(),
          });
          return;
        }

        // 검사 3: public API를 통하지 않은 import (슬라이스 내부 직접 접근)
        // 다른 레이어의 슬라이스 내부 파일을 직접 import하는 경우 감지
        if (importedLayer !== layer && importedSlice) {
          const aliasGroup = `(?:${aliasPatterns.join('|')})`;
          const fullImportPath = aliasMatch
            ? line.match(new RegExp(`from\\s+['"]${aliasGroup}${importedLayer}/${importedSlice}/([^'"]+)`))?.[1]
            : null;
          if (fullImportPath && fullImportPath !== 'index') {
            violations.push({
              file: path.relative(srcDir, file),
              line: idx + 1,
              type: 'public-api',
              message: `${importedLayer}/${importedSlice}의 내부 파일 직접 import (index.ts를 통해 접근하세요)`,
              importStatement: line.trim(),
            });
          }
        }
      });
    }
  }

  return violations;
}

// 실행
const violations = findViolations(SRC_ROOT);

if (violations.length > 0) {
  const byType = {
    layer: violations.filter((v) => v.type === 'layer'),
    'cross-slice': violations.filter((v) => v.type === 'cross-slice'),
    'public-api': violations.filter((v) => v.type === 'public-api'),
  };

  console.error('❌ FSD 아키텍처 위반 발견:\n');

  if (byType.layer.length > 0) {
    console.error(`--- 레이어 의존성 위반 (${byType.layer.length}건) ---`);
    byType.layer.forEach((v) => {
      console.error(`  ${v.file}:${v.line}`);
      console.error(`    ${v.message}`);
      console.error(`    ${v.importStatement}\n`);
    });
  }

  if (byType['cross-slice'].length > 0) {
    console.error(`--- Cross-Slice 위반 (${byType['cross-slice'].length}건) ---`);
    byType['cross-slice'].forEach((v) => {
      console.error(`  ${v.file}:${v.line}`);
      console.error(`    ${v.message}`);
      console.error(`    ${v.importStatement}\n`);
    });
  }

  if (byType['public-api'].length > 0) {
    console.error(`--- Public API 위반 (${byType['public-api'].length}건) ---`);
    byType['public-api'].forEach((v) => {
      console.error(`  ${v.file}:${v.line}`);
      console.error(`    ${v.message}`);
      console.error(`    ${v.importStatement}\n`);
    });
  }

  console.error(`\n총 ${violations.length}건의 위반`);
  process.exit(1);
} else {
  console.log('✅ FSD 아키텍처 규칙 검증 통과');
}
