// Generated by harness-setup skill. Rules derived from project profile.
// 레이어 기반 아키텍처 검증 스크립트 템플릿
//
// 사용법: npx tsx scripts/structural-test.ts
// 이 파일은 템플릿이다. SKILL.md가 프로필 기반으로 LAYER_RULES를 치환하여
// 프로젝트의 scripts/structural-test.ts에 생성한다.

import * as fs from 'fs';
import * as path from 'path';

// {{LAYER_RULES}} — 프로필의 architecture.layers.rules로 치환
// 예시 (react-next 프리셋 기준):
const LAYER_RULES: Record<string, string[]> = {
  'types':      [],
  'config':     ['types'],
  'lib':        ['types', 'config'],
  'services':   ['types', 'config', 'lib'],
  'hooks':      ['types', 'config', 'lib', 'services'],
  'components': ['types', 'config', 'lib', 'hooks'],
  'pages':      ['types', 'config', 'lib', 'services', 'hooks', 'components'],
  'app':        ['types', 'config', 'lib', 'services', 'hooks', 'components', 'pages'],
};

// {{PATH_ALIAS}} — 프로필의 pathAlias로 치환 (예: '@/' 또는 ['@/', '~/'])
// 문자열이면 단일 alias, 배열이면 다중 alias
const PATH_ALIAS: string | string[] = '@/';

// {{SRC_ROOT}} — 프로필의 srcRoot로 치환 (예: './src')
const SRC_ROOT = './src';

// --- 이하 코드는 치환 없이 그대로 사용 ---

interface Violation {
  file: string;
  line: number;
  importedLayer: string;
  currentLayer: string;
  importStatement: string;
}

function getFilesRecursive(dir: string): string[] {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  return entries.flatMap((entry) => {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) return getFilesRecursive(fullPath);
    if (/\.(ts|tsx)$/.test(entry.name) && !/\.test\.(ts|tsx)$/.test(entry.name)) {
      return [fullPath];
    }
    return [];
  });
}

function resolveLayerFromRelativePath(
  filePath: string,
  importPath: string,
  srcDir: string,
): string | null {
  const fileDir = path.dirname(filePath);
  const resolved = path.resolve(fileDir, importPath);
  const relative = path.relative(srcDir, resolved);
  if (relative.startsWith('..')) return null;
  const topFolder = relative.split(path.sep)[0];
  return LAYER_RULES[topFolder] !== undefined ? topFolder : null;
}

function findViolations(srcDir: string): Violation[] {
  const violations: Violation[] = [];
  const aliases = Array.isArray(PATH_ALIAS) ? PATH_ALIAS : [PATH_ALIAS];
  const aliasPatterns = aliases.map((a) => a.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'));
  const aliasRegex = new RegExp(`from\\s+['"](?:${aliasPatterns.join('|')})([\\w-]+)`);
  // import 및 re-export 구문 모두 감지: import ... from '...' / export { ... } from '...'
  const importOrReExportRegex = /(?:import|export)\s+.*from\s+['"](\.\.?\/[^'"]+)/;
  const relativeRegex = importOrReExportRegex;

  for (const [layer, allowed] of Object.entries(LAYER_RULES)) {
    const layerDir = path.join(srcDir, layer);
    if (!fs.existsSync(layerDir)) continue;

    const files = getFilesRecursive(layerDir);

    for (const file of files) {
      const content = fs.readFileSync(file, 'utf-8');
      const lines = content.split('\n');

      lines.forEach((line, idx) => {
        let importedLayer: string | null = null;

        // 1. alias import 검사: @/layer/...
        const aliasMatch = line.match(aliasRegex);
        if (aliasMatch) {
          importedLayer = aliasMatch[1];
        }

        // 2. 상대 경로 import 검사: ../../layer/...
        if (!importedLayer) {
          const relMatch = line.match(relativeRegex);
          if (relMatch) {
            importedLayer = resolveLayerFromRelativePath(file, relMatch[1], srcDir);
          }
        }

        if (!importedLayer) return;
        if (importedLayer === layer) return; // 같은 레이어 내 import는 허용

        if (!allowed.includes(importedLayer)) {
          violations.push({
            file: path.relative(srcDir, file),
            line: idx + 1,
            importedLayer,
            currentLayer: layer,
            importStatement: line.trim(),
          });
        }
      });
    }
  }

  return violations;
}

// 실행
const violations = findViolations(SRC_ROOT);

if (violations.length > 0) {
  console.error('❌ 아키텍처 위반 발견:\n');
  violations.forEach((v) => {
    console.error(`  ${v.file}:${v.line}`);
    console.error(`    ${v.currentLayer} → ${v.importedLayer} (금지)`);
    console.error(`    ${v.importStatement}\n`);
  });
  console.error(`총 ${violations.length}건의 위반`);
  process.exit(1);
} else {
  console.log('✅ 아키텍처 규칙 검증 통과');
}
